In [1]:
import numpy as np

d1=np.array([3,5,7,2])

print("Data type: ",d1.dtype)
d1

Data type:  int64


array([3, 5, 7, 2])

In [3]:
import numpy as np

d1=np.array(["A","B"])
d1=np.array([1,2,"A","B"])
# d1=np.array([1,2,"A","B",5.6,8.67])

print("Data type: ",d1.dtype)
d1


Data type:  <U21


array(['1', '2', 'A', 'B'], dtype='<U21')

In [5]:
# d1=np.array([5.6,8.67],dtype=np.int64)
d1=np.array([5.6,8.67],dtype="i")

print("Data type: ",d1.dtype)
d1


Data type:  int32


array([5, 8], dtype=int32)

In [6]:

d1=np.array([5.6,8.67],dtype="i")
# new = np.int16(d1)
new = np.int16(d1)

print("Data type: ",new.dtype)
new

Data type:  int16


array([5, 8], dtype=int16)

In [7]:

d1=np.array([5,8])
new = d1.astype(float)

print("Data type: ",new.dtype)
new

Data type:  float64


array([5., 8.])

In [8]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([3,6,2,7])

varAdd1=var1+var2
varSub2=var1-var2
varMul3=var1*var2
varDiv4=var1/var2

print("Addition is : ",varAdd1)
print("Subtraction is : ",varSub2)
print("Multilication is : ",varMul3)
print("Divide is : ",varDiv4)

Addition is :  [ 4  8  5 11]
Subtraction is :  [-2 -4  1 -3]
Multilication is :  [ 3 12  6 28]
Divide is :  [0.33333333 0.33333333 1.5        0.57142857]


In [9]:
import numpy as np
var1=np.array([1,2,3,4])

print("Vector plus: ",var1+2)
print("Vector minus: ",var1-1)
print("Vector multiply: ",var1*3)
print("Vector divide: ",var1/2)
print("Vector floor divide: ",var1//2)
print("Vector Modulous: ",var1%3)
print("Vector Modulous: ",var1**2)

Vector plus:  [3 4 5 6]
Vector minus:  [0 1 2 3]
Vector multiply:  [ 3  6  9 12]
Vector divide:  [0.5 1.  1.5 2. ]
Vector floor divide:  [0 1 1 2]
Vector Modulous:  [1 2 0 1]
Vector Modulous:  [ 1  4  9 16]


In [ ]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])

# newVal=np.add(var1,var2)
# newVal=np.add(var1,3)
# newVal=np.multiply(var1,3)
# newVal=np.mod(var1,3)
# newVal

array([1, 2, 0, 1])