In [ ]:
import numpy as np

arr=np.array([3,5,7,9])

# print(arr)
print(type(arr))
print(arr.ndim)
# arr



<class 'numpy.ndarray'>
1


In [4]:
arr2=np.array([[3,5,7,9],[5,3,7,2],[2,5,8,2]])

# arr2
print(arr2)
print(arr2.ndim)

[[3 5 7 9]
 [5 3 7 2]
 [2 5 8 2]]
2


In [5]:
arr3=np.array([[[5,3,7,2],[2,5,8,2],[4,5,7,2]]])

# arr2
print(arr3)
print(arr3.ndim)

[[[5 3 7 2]
  [2 5 8 2]
  [4 5 7 2]]]
3


In [6]:
arrN=np.array([1,3,5,6,5],ndmin=10)

# arr2
print(arrN)
print(arrN.ndim)

[[[[[[[[[[1 3 5 6 5]]]]]]]]]]
10


In [ ]:
import numpy as np

zerosArr1=np.zeros(4)
zerosArr2=np.zeros((3,3))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[0. 0. 0. 0.]
--------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
zerosArr1=np.ones(4)
zerosArr2=np.ones((3,3))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[1. 1. 1. 1.]
--------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# arrEmp=np.empty((4,3)) # Random garbage values

# arrEmp

# arrRange=np.arange(5)
# print(arrRange)
arrRange=np.arange(5)*2
arrRange

array([0, 2, 4, 6, 8])

In [15]:
# arrDiogonal=np.eye(4)
# arrDiogonal

arrDiogonal=np.eye(3,4)
arrDiogonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [19]:
arr_lin=np.linspace(0,20,num=5)
arr_lin

array([ 0.,  5., 10., 15., 20.])

In [22]:
var1=np.random.rand(5)
var2=np.random.rand(3,3)
var3=np.random.randn(5)
var4=np.random.randn(3,4)

print("Random 1d Array Between 0 to 1:",var1)
print("Random 2d Array Between 0 to 1:",var2)
print("Random 1d Array Between closed to zero Negative Positive:",var3)
print("Random 2d Array Between closed to zero Negative Positive:",var4)


Random 1d Array Between 0 to 1: [0.37350013 0.40179546 0.26516728 0.13999922 0.00072911]
Random 2d Array Between 0 to 1: [[0.64574603 0.15249573 0.60280168]
 [0.02801106 0.68627671 0.30208617]
 [0.16072085 0.8608685  0.87499107]]
Random 1d Array Between closed to zero Negative Positive: [ 1.6077194  -0.7713746  -0.67862477 -0.54393064  0.45796191]
Random 2d Array Between closed to zero Negative Positive: [[-1.983447   -1.35185457 -1.46519405  0.65513673]
 [ 0.43340207  0.46351764  0.91203583 -1.12185539]
 [-2.15279763  0.25843617  0.38918702  0.79374119]]


In [ ]:
var5=np.random.ranf(5)
var6=np.random.ranf((4,5))
var7=np.random.randint(4,10,5)


print("Random 1d Array Between [0,1):",var5)
print("Random 2d Array Between [0,1):",var6)
print("Random integer 1d Array Between 4 to 10:",var7)

Random 1d Array Between [0,1): [0.16598241 0.06853818 0.59121861 0.36215931 0.61646124]
Random 2d Array Between [0,1): [[0.20775421 0.67137863 0.00522788 0.10687005 0.06669236]
 [0.05929488 0.26997756 0.37148132 0.34495457 0.49572946]
 [0.84223281 0.60499639 0.57546597 0.15596137 0.97292849]
 [0.39385053 0.79287722 0.48511789 0.62642727 0.66293119]]
Random integer 1d Array Between 4 to 10: [4 9 7 6 6]
